# The MIT License (MIT).
#
# Copyright (c) 2023 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.

name: Check pull request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.10", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ matrix.python_version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
      - name: Run tests via pytest
        run: poetry run pytest

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ github.workspace }}/checker
      - name: Clone other repo
        uses: actions/checkout@v5
        with:
          repository: "blablatdinov/quranbot-aiogram"
          path: ${{ github.workspace }}/quranbot-aiogram
      - name: Setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-3.12-${{ hashFiles('**/poetry.lock') }}
      - name: Install deps
        run: cd ${{ github.workspace }}/quranbot-aiogram && poetry install && poetry add ${{ github.workspace }}/checker
      - name: Test
        run: cd ${{ github.workspace }}/quranbot-aiogram && poetry run flake8 src

  # lint:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: "3.13"
  #   - name: Install Poetry
  #     uses: snok/install-poetry@v1.3.4
  #     with:
  #       virtualenvs-create: true
  #       virtualenvs-in-project: true
  #       installer-parallel: true
  #   - name: Load cached venv
  #     id: cached-poetry-dependencies
  #     uses: actions/cache@v3
  #     with:
  #       path: .venv
  #       key: venv-3.13-${{ hashFiles('**/poetry.lock') }}
  #   - name: Install dependencies
  #     if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
  #   - name: flake8
  #     run: flake8 pyeo tests
  #   - name: mypy
  #     run: mypy pyeo tests
